Repository sprinteins/oscd-plugins, pull requests merged in 2024-10, with the labels that each got.

#107 fix(uilib): remove deprecated types package dependency
  packages/uilib/package.json
  pnpm-lock.yaml
Labels: Kind: Bug

#118 feat(type-designer): Display Board with Six Parts
  packages/core/src/constants/element.constant.ts
  packages/core/src/scd-queries/data-type-templates/types.data-type-templates.d.ts
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/components/elements-type-container/column-type.d.ts
  packages/plugins/type-designer/src/components/elements-type-container/columns.svelte
  packages/plugins/type-designer/src/components/elements-type-container/content-card.svelte
  packages/plugins/type-designer/src/components/elements-type-container/create-new-item.ts
  packages/plugins/type-designer/src/components/elements-type-container/data-type-templates.d.ts
  packages/plugins/type-designer/src/components/elements-type-container/element-type-container.svelte
  packages/plugins/type-designer/src/components/elements-type-container/tool-bar.svelte
  packages/plugins/type-designer/src/components/index.ts
  packages/plugins/type-designer/src/plugin.svelte
  packages/ui/src/assets/styles/theme.css
  packages/ui/src/components/icons/icons-draw.ts
  pnpm-lock.yaml
Labels: Epic: TypeDesigner

#150 fix(ui): add workaround component to fix the hover issue on IconButton
  package.json
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview.ts
  packages/ui/package.json
  packages/ui/src/assets/styles/theme.css
  packages/ui/src/components/dev/menu-bar.dev.stories.svelte
  packages/ui/src/components/dev/menu-bar.dev.stories.ts
  packages/ui/src/components/dev/menu-bar.dev.svelte
  packages/ui/src/components/icons/icon-wrapper.mdx
  packages/ui/src/components/icons/icon-wrapper.stories.svelte
  packages/ui/src/components/icons/icon-wrapper.stories.ts
  packages/ui/src/components/icons/icon-wrapper.svelte
  packages/ui/src/components/icons/types.icon.d.ts
  packages/ui/src/components/index.ts
  packages/ui/src/components/smui-wrapper/custom-icon-button.svelte
  packages/ui/src/components/smui-wrapper/icon-wrapper.stories.svelte
  packages/ui/src/components/smui-wrapper/index.ts
  packages/ui/src/components/storybook/decorators/theme-decorator.svelte
  packages/ui/src/components/theme/theme.svelte
  packages/ui/src/utils/index.ts
  packages/ui/src/utils/style.utils.ts
Labels: Epic: TypeDesigner, Kind: Bug
