Repository sprinteins/oscd-plugins, pull requests merged in 2025-02, with the labels that each got.

#288 Feat/baycontainers
  packages/plugins/communication-explorer/package.json
  packages/plugins/communication-explorer/vite.config.ts
  packages/uilib/src/lib/components/diagram/bay-container/bay-container.svelte
  packages/uilib/src/lib/plugins/communication-explorer/_func-layout-calculation/node-layout.ts
Labels: Epic: Communication Explorer

#297 Feat/type designer delete ref
  packages/core/api/src/plugin/v1/xml/constants.ts
  packages/core/api/src/plugin/v1/xml/create-custom.ts
  packages/core/api/src/plugin/v1/xml/create-standard.ts
  packages/core/standard/src/ed2/rev1/unstable/IEC61850-90-30/definition/substation/types.equipment.d.ts
  packages/core/ui-svelte/src/lib/headless/actions/useInitSsdTemplate.svelte.ts
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/headless/stores/type-elements/consolidate-types.helper.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/store.svelte.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/types.d.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/wrapper.helper.ts
  packages/plugins/type-designer/src/ui/components/column/column.svelte
  packages/plugins/type-designer/src/ui/components/column/element-card.svelte
  packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
  packages/plugins/type-designer/src/ui/components/element-card/card-menu.svelte
  packages/plugins/type-designer/src/ui/components/element-card/type-card.svelte
  packages/plugins/type-designer/src/ui/components/sidebar-wrapper.svelte
Labels: Epic: TypeDesigner, Kind: Feature

#298 Feat/type designer search input
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/headless/stores/type-elements/filter.helper.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/store.svelte.ts
  packages/plugins/type-designer/src/ui/components/column/column.svelte
Labels: Epic: TypeDesigner, Kind: Feature

#325 [FEATURE]: Add logic for identifying bay and voltageLevel of message publisher
  packages/plugins/auto-doc/src/stores/signallist.store.ts
Labels: Epic: AutoDoc

#318 fixing way too large zoom sometimes happening when using focus mode
  packages/uilib/src/lib/components/diagram/diagram.svelte
Labels: Epic: Communication Explorer
