Repository sprinteins/oscd-plugins, pull requests merged in 2025-03, with the labels that each got.

#326 [FEATURE]: Duplicate Template
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/data-table/data-table.svelte
  packages/plugins/auto-doc/src/pages/template-overview/template-overview.svelte
  packages/plugins/auto-doc/src/stores/doc-templates.store.spec.ts
  packages/plugins/auto-doc/src/stores/doc-templates.store.ts
Labels: Epic: AutoDoc

#319 [FEATURE]: Edit template
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/doc/libraies.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/data-table/data-table.svelte
  packages/plugins/auto-doc/src/components/elements/signal-list-element/signal-list-element.svelte
  packages/plugins/auto-doc/src/components/template-builder/template-builder.svelte
  packages/plugins/auto-doc/src/constants/index.ts
  packages/plugins/auto-doc/src/constants/routing.ts
  packages/plugins/auto-doc/src/pages/template-creation/template-creation.svelte
  packages/plugins/auto-doc/src/pages/template-overview/template-overview.svelte
  packages/plugins/auto-doc/src/routes/routes.ts
  packages/plugins/auto-doc/src/stores/doc-templates.store.spec.ts
  packages/plugins/auto-doc/src/stores/doc-templates.store.ts
  packages/plugins/auto-doc/src/stores/signallist.store.ts
Labels: Epic: AutoDoc

#349 [FEAT]: Use Zipcelx library to export Signal List as Excel
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/utils/pdfGenerator.ts
  pnpm-lock.yaml
Labels: Epic: AutoDoc

#348 Feat: Rich Text Editor
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/elements/text-element/text-element.svelte
  packages/plugins/auto-doc/src/stores/placeholder.store.spec.ts
  packages/plugins/auto-doc/src/utils/pdfGenerator.ts
  pnpm-lock.yaml
Labels: Epic: AutoDoc

#242 Feat/baylabels
  packages/core/legacy/src/scd-queries/ied/service.ied.ts
  packages/core/legacy/src/scd-queries/scd-query.ts
  packages/plugins/communication-explorer/CHANGELOG.md
  packages/uilib/src/lib/components/diagram/+page.svelte
  packages/uilib/src/lib/components/diagram/diagram.svelte
  packages/uilib/src/lib/components/diagram/ied-element/+page.svelte
  packages/uilib/src/lib/components/diagram/ied-element/ied-element.svelte
  packages/uilib/src/lib/components/diagram/nodes.ts
  packages/uilib/src/lib/plugins/communication-explorer/_func-layout-calculation/config.ts
  packages/uilib/src/lib/plugins/communication-explorer/_func-layout-calculation/node-layout-ieds.ts
  packages/uilib/src/lib/plugins/communication-explorer/_func-layout-calculation/node-layout.ts
  packages/uilib/src/lib/plugins/communication-explorer/_store-preferences/preferences-store.ts
  packages/uilib/src/lib/plugins/communication-explorer/_store-view-filter/selected-filter-store-functions.ts
  packages/uilib/src/lib/plugins/communication-explorer/services/ied.ts
  packages/uilib/src/lib/plugins/communication-explorer/sidebar/sidebar.svelte
  packages/uilib/src/lib/plugins/communication-explorer/telemetry-view/telemetry-view.svelte
Labels: Epic: Communication Explorer

#355 feat: duplicate modul
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/src/components/element-wrapper/element-wrapper.svelte
  packages/plugins/auto-doc/src/components/template-builder/template-builder.svelte
  packages/plugins/auto-doc/src/plugin.svelte
  packages/plugins/auto-doc/src/stores/doc-templates.store.spec.ts
  packages/plugins/auto-doc/src/stores/doc-templates.store.ts
  packages/plugins/auto-doc/src/stores/events.store.ts
  packages/plugins/auto-doc/src/stores/plugin.store.ts
Labels: Epic: AutoDoc, Kind: Feature

#353 AutoDoc UX adjustments
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/src/components/data-table/data-table.svelte
  packages/plugins/auto-doc/src/components/tooltip/tooltip.svelte
  packages/plugins/auto-doc/src/pages/template-creation/template-creation.svelte
  packages/plugins/auto-doc/src/pages/template-overview/template-overview.svelte
Labels: Epic: AutoDoc

#357 feat: move modul
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/src/components/element-wrapper/element-wrapper.svelte
  packages/plugins/auto-doc/src/components/template-builder/template-builder.svelte
  packages/plugins/auto-doc/src/constants/elements.ts
  packages/plugins/auto-doc/src/constants/index.ts
  packages/plugins/auto-doc/src/stores/doc-templates.store.ts
  packages/plugins/auto-doc/src/stores/events.store.ts
Labels: Epic: AutoDoc, Kind: Feature

#374 Fix: Direct doc access
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/template-builder/template-builder.svelte
  packages/plugins/auto-doc/src/stores/doc-templates.store.spec.ts
  packages/plugins/auto-doc/src/stores/doc-templates.store.ts
  packages/plugins/auto-doc/src/stores/events.store.ts
  pnpm-lock.yaml
Labels: Epic: AutoDoc

#358 feat(259): Auto doc import template
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/file-selector/file-selector.svelte
  packages/plugins/auto-doc/src/components/index.ts
  packages/plugins/auto-doc/src/pages/template-overview/template-overview.svelte
  packages/plugins/auto-doc/src/stores/doc-templates.store.spec.ts
  packages/plugins/auto-doc/src/stores/doc-templates.store.ts
  packages/plugins/auto-doc/src/stores/events.store.ts
  packages/plugins/auto-doc/src/utils/index.ts
  packages/plugins/auto-doc/src/utils/xml-util.ts
  pnpm-lock.yaml
Labels: Epic: AutoDoc, Kind: Feature

#354 Signallist DND
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/data-table/data-table.svelte
  packages/plugins/auto-doc/src/components/elements/signal-list-element/signal-list-element.svelte
  packages/plugins/auto-doc/src/components/elements/signal-list-element/signal-row.svelte
  packages/plugins/auto-doc/src/components/elements/signal-list-element/types.signal-list.d.ts
  packages/plugins/auto-doc/src/stores/signal-dnd.store.ts
Labels: Epic: AutoDoc

#382 fix(type-designer): add validation to input name in the sidebar
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/headless/stores/sidebar.svelte.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/store.svelte.ts
  packages/plugins/type-designer/src/ui/components/import/import-select.svelte
  packages/plugins/type-designer/src/ui/components/sidebar-wrapper.svelte
Labels: Epic: TypeDesigner

#377 feat(type-designer): deep import
  .github/pull_request_template.md
  packages/core/api/src/plugin/v1/events/createAndDispatch.ts
  packages/core/api/src/plugin/v1/utils/helpers.ts
  packages/core/ui-svelte/src/lib/headless/stores/SSD/ssd.svelte.ts
  packages/core/ui-svelte/src/lib/headless/stores/dialog.svelte.ts
  packages/core/ui-svelte/src/lib/ui/shadcn-workaround/dialog.workaround.svelte
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/headless/constants/type-elements.ts
  packages/plugins/type-designer/src/headless/stores/imports/import-attribute.helper.ts
  packages/plugins/type-designer/src/headless/stores/imports/import-naming.helper.ts
  packages/plugins/type-designer/src/headless/stores/imports/imported-refs-crud-operation.helper.ts
  packages/plugins/type-designer/src/headless/stores/imports/imported-tree-handler.helper.ts
  packages/plugins/type-designer/src/headless/stores/imports/imported-type-crud-operation.helper.ts
  packages/plugins/type-designer/src/headless/stores/imports/load-file.helper.ts
  packages/plugins/type-designer/src/headless/stores/imports/store.svelte.ts
  packages/plugins/type-designer/src/headless/stores/imports/types.d.ts
  packages/plugins/type-designer/src/headless/stores/index.ts
  packages/plugins/type-designer/src/headless/stores/sidebar.svelte.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/store.svelte.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/type-crud-operation.helper.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/type-naming.helper.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/types.d.ts
  packages/plugins/type-designer/src/plugin.svelte
  packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
  packages/plugins/type-designer/src/ui/components/element-card/type-card.svelte
  packages/plugins/type-designer/src/ui/components/import/compas/import-dialog.svelte
  packages/plugins/type-designer/src/ui/components/import/import-container.svelte
  packages/plugins/type-designer/src/ui/components/import/import-select.svelte
  packages/plugins/type-designer/src/ui/components/import/update-confirmation-dialog.svelte
  packages/plugins/type-designer/src/ui/components/sidebar-wrapper.svelte
Labels: Epic: TypeDesigner

#383 [FEATURE]: Placeholder on PDF based on XPath
  packages/plugins/auto-doc/src/plugin.svelte
  packages/plugins/auto-doc/src/stores/placeholder.store.ts
  pnpm-lock.yaml
Labels: Epic: AutoDoc

#386 feat(type-designer): add ref occurrence
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/headless/stores/type-elements/consolidate-types.helper.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/types.d.ts
  packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
Labels: Epic: TypeDesigner

#385 Drag and Drop adaptions
  packages/plugins/type-designer/src/headless/stores/dnd.svelte.ts
  packages/plugins/type-designer/src/ui/components/column/single-column.svelte
  packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
Labels: Epic: TypeDesigner

#388 Feat: Table module
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/dialog/create-table-dialog.svelte
  packages/plugins/auto-doc/src/components/elements/index.ts
  packages/plugins/auto-doc/src/components/elements/table-element/table-column.svelte
  packages/plugins/auto-doc/src/components/elements/table-element/table-element.svelte
  packages/plugins/auto-doc/src/components/elements/types.elements.d.ts
  packages/plugins/auto-doc/src/components/template-builder/template-builder.svelte
  packages/plugins/auto-doc/src/utils/pdfGenerator.ts
  pnpm-lock.yaml
Labels: Epic: AutoDoc, Kind: Feature

#404 Show Access Points in DO Bar
  packages/plugins/io-center/src/headless/constants/constants.ts
  packages/plugins/io-center/src/ied/object-tree.type.d.ts
  packages/plugins/io-center/src/query.svelte.ts
  packages/plugins/io-center/src/ui/components/object-tree/object-tree.svelte
Labels: Epic: I/O Center, Kind: Feature

#400 Feat/type designer bay ref badge
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
  packages/plugins/type-designer/src/ui/components/element-card/type-card.svelte
Labels: Epic: TypeDesigner

#399 Feat/type designer duplicate ref
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/headless/stores/type-elements/common-crud-operation.helper.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/store.svelte.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/type-crud-operation.helper.ts
  packages/plugins/type-designer/src/ui/components/element-card/card-menu.svelte
  packages/plugins/type-designer/src/ui/components/sidebar/sidebar-wrapper.svelte
Labels: Epic: TypeDesigner

#406 [BUGFIX]: Fill placeholder on pdf generation
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/elements/text-element/text-element.svelte
  packages/plugins/auto-doc/src/utils/pdfGenerator.ts
Labels: Epic: AutoDoc, Kind: Bug

#401 [FEATURE]: Disable template import when is "Master" template
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/pages/template-overview/template-overview.svelte
  packages/plugins/auto-doc/src/stores/doc-templates.store.spec.ts
  packages/plugins/auto-doc/src/stores/doc-templates.store.ts
Labels: Epic: AutoDoc

#407 Feat/type designer ux adjustments
  packages/plugins/type-designer/src/headless/constants/type-elements.ts
  packages/plugins/type-designer/src/headless/stores/dnd.svelte.ts
  packages/plugins/type-designer/src/headless/stores/imports/imported-type-crud-operation.helper.ts
  packages/plugins/type-designer/src/headless/stores/type-elements/types.d.ts
  packages/plugins/type-designer/src/ui/components/column/single-column.svelte
  packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
  packages/plugins/type-designer/src/ui/components/element-card/type-card.svelte
Labels: Epic: TypeDesigner

#411 feat(type-designer): increment version + changelog update
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
Labels: Epic: TypeDesigner

#396 Feat: Images in PDF
  packages/plugins/auto-doc/CHANGELOG.md
  packages/plugins/auto-doc/package.json
  packages/plugins/auto-doc/src/components/elements/image-element/image-element.svelte
  packages/plugins/auto-doc/src/components/elements/image-element/types.image.d.ts
  packages/plugins/auto-doc/src/utils/pdfGenerator.ts
Labels: Epic: AutoDoc, Kind: Feature

#412 fix(type-designer): resolve import statement & restrict dnd dropzones
  packages/plugins/type-designer/CHANGELOG.md
  packages/plugins/type-designer/package.json
  packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
Labels: Epic: TypeDesigner

#413 Feat: UX Adjustments in IO Center (2)
  packages/plugins/io-center/src/ied/ied-select.svelte
Labels: Epic: I/O Center, Kind: Feature
